version: "3.8"

services:
  app-filament:
    build: .
    container_name: filament_v4_app
    restart: always
    env_file: .env
    # MENGGUNAKAN NAMED VOLUME AGAR VENDOR TIDAK HILANG
    volumes:
      - herama-code:/var/www
    networks:
      - herama-frontend

  web-server:
    image: nginx:alpine
    container_name: filament_nginx
    restart: always
    ports:
      - "8585:80"
    volumes:
      # NGINX MEMBACA KODE DARI VOLUME YANG SAMA
      - herama-code:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-filament
    networks:
      - herama-frontend

networks:
  herama-frontend:
    driver: bridge

# DEFINISIKAN VOLUME DI SINI
volumes:
  herama-code:
