version: "3.8"

services:
  # Service Laravel
  app-filament:
    build: .
    container_name: filament_v4_app
    restart: always
    env_file: .env
    # HAPUS ATAU KOMENTARI BAGIAN VOLUMES INI
    # volumes:
    #   - .:/var/www
    networks:
      - herama-frontend

  # Service Nginx
  web-server:
    image: nginx:alpine
    container_name: filament_nginx
    restart: always
    ports:
      - "8585:80"
    volumes:
      # HAPUS VOLUMES KODE BERIKUT
      # - .:/var/www
      # BIARKAN CONFIG NGINX INI TETAP ADA
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-filament
    networks:
      - herama-frontend

networks:
  herama-frontend:
    driver: bridge
